# https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models

[CONSTANTS]
max_context_length = 16384

[GPT4V_DETAILS]
deployment = "GPT4Vision"
model = "vision-preview"
context_length = 128000
input_cost = 0.01
output_cost = 0.03
tpm = 30000
rpm = 30
regions = ["westus"]

[GPT4_DETAILS]
deployment = "4Turbo1106"
model = "gpt-4-1106-preview"
context_length = 128000
input_cost = 0.01
output_cost = 0.03
tpm = 155000
rpm = 930
regions = ["canadaeast"]

[GPT3_DETAILS]
deployment = "35Turbo1106"
model = "gpt-3.5-turbo-0125"
context_length = 16384
input_cost = 0.0005
output_cost = 0.0015
tpm = 110000
rpm = 660
regions = ["canadaeast"]

[EMBEDDING_DETAILS]
deployment = "embedding"
model = "text-embedding-3-large"
context_length = 8192
input_cost = 0.00013
output_cost = 0.00013
tpm = 350000
rpm = 2100
regions = ["canadaeast"]

# https://milvus.io/blog/select-index-parameters-ivf-index.md
[MILVUS_CONFIG]
EMBEDDING_SIZE = 3072
METRIC_TYPE = "COSINE"
INDEX_TYPE = "IVF_FLAT"
NLIST = 2048
NPROBE = 64
SHARDS = 2
INDEX_FILE_SIZE = 2048
