[repo_summaries]
"https://github.com/Mayil-AI-Sandbox/area-of-shapes" = "Small python program to calculate the area of different shapes"

[documentation.shopify]
collection = "shopify_documentation"
description = "Shopify’s API reference and templating documentation. You have access to everything from the Admin API and app extensions to templating tools documentation pertaining to a Shopify store"
